### ISSUE TITLE
Error in existing project

### ISSUE THREAD

**Issue by heuvelc** [RoelandSalij/GoogleAuthenticator#1]
Hi Roeland,

The demo project works fine but when implementing this in an existing Mendix project I always run into this error:

java.lang.NoSuchMethodError: org.apache.http.client.utils.URLEncodedUtils.encPath(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String;
    at org.apache.http.client.utils.URIBuilder.encodePath(URIBuilder.java:175)
    at org.apache.http.client.utils.URIBuilder.buildString(URIBuilder.java:136)
    at org.apache.http.client.utils.URIBuilder.toString(URIBuilder.java:470)
    at com.warrenstrange.googleauth.GoogleAuthenticatorQRGenerator.getOtpAuthTotpURL(GoogleAuthenticatorQRGenerator.java:181)
    at com.warrenstrange.googleauth.GoogleAuthenticatorQRGenerator.getOtpAuthURL(GoogleAuthenticatorQRGenerator.java:133)

I have tried various approaches including a full cleanup and rebuild of the userlib but without any succes.

Suggestions?

Regards

Cees

**Comment by RoelandSalij** [comment]
Hi Cees,
Thanks for your feedback.
I will look into this. I try to look at it this week!

**Comment by RoelandSalij** [comment]
Hi Cees, 
I didn't succeed in reproducing the problem succesfully in existing projects.
I do suspect however that there is a conflict with java libraries.
Can you list the libraries in your userlib? 
Do you have multiple versions of the httpclient jar?

**Comment by heuvelc** [comment]
Hi Roeland,

I completely rebuild the userlib for the project based on earlier experiences I had and assured that there is only one version but this didnot solve the problem. Howver after some more puzzling I discovered that one of the other "components" loads apache-httpcomponents-httpclient into the userlib directory. This looks to be al very old (2011) version of the http client and this causes the problem. When I remove this from the userlib the java errors disappear.

I still have to figure out if everything else continues to work when I remove the file but at least I know where to look :>)

Thanks for your support

Regards

Cees

[apache-httpcomponents-httpclient.zip](https://github.com/RoelandSalij/GoogleAuthenticator/files/592139/apache-httpcomponents-httpclient.zip)

**Comment by RoelandSalij** [comment]
Thanks Cees, good to hear that!
