### ISSUE TITLE
Kan QR-code niet interpreteren

### ISSUE THREAD

**Issue by wouter-kremer** [RoelandSalij/GoogleAuthenticator#2]
Hi Roeland,

Thanks for your great widget. I am trying to get it work in al local project. Everyting seems fine but when i test it in google authenticator on my mobile device i get the message: Kan QR-code niet interpreteren.

Does it only work in cloud enviroments?
Can you give me a hint to solve this?

Thanks in advance for your quick answer.  

![2018-10-18 12_24_21-daywize feedbackportal - home](https://user-images.githubusercontent.com/19794624/47148360-d6963980-d2d0-11e8-83b4-79887fb2ddc2.png)

![2018-10-18 12_28_06-support app main line - mendix modeler 7 18 1](https://user-images.githubusercontent.com/19794624/47148593-60de9d80-d2d1-11e8-921b-b60f711a642a.png)

![2018-10-18 12_28_23-support app main line - mendix modeler 7 18 1](https://user-images.githubusercontent.com/19794624/47148598-650abb00-d2d1-11e8-9f5f-52ddbca26a49.png)

**Comment by wouter-kremer** [comment]
Laat maar, we hebben het gevonden. Er ontbreekt iets in de documentatie:

De string voor qr-code moet alsvolgt zijn opgebouwd. 
otpauth://totp/$AppName:$UserName?secret=$SecretKey

**Comment by RoelandSalij** [comment]
Thanks for the feedback. I've improved the action to return this string and updated the documentation.
